### ISSUE TITLE
HTTPS Required Error while compile

### ISSUE THREAD

**Issue by 321drago** [openkm/sdk4j-with-dependences#3]
Hello everybody,
I tried to build the jar, but get a exception: 
_Plugin org.apache.maven.plugins:maven-clean-plugin:2.4.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.4.1: Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:2.4.1 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.4.1/maven-clean-plugin-2.4.1.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. -> [Help 1]_

**Comment by 321drago** [comment]
I changed the line 57 but get still the same Error.

**Comment by darkman97i** [comment]
Download the current master, I applied a changed there and should working ( I tested before from my side )
